
services:
  - type: web
    name: damask-shop
    env: node
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production node dist/server/index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /
