services:
  - type: web
    name: damask-shop
    runtime: docker
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /